name: Build and Package

on:
  push:
    branches:
      - branchAutoPackage
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential debhelper autotools-dev autoconf automake

      - name: Configure and Build
        run: |
          autoreconf --install
          ./configure
          make

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc
          
      - name: Upload .deb package
        uses: actions/upload-artifact@v3
        with:
          name: my-package
          path: ../*.deb 
